config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  get '/homes/about', to: 'homes#about'
  devise_for :users
  root to: "homes#top"
  resources :books
  resources :users, only: [:show, :edit, :index, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user

validates :title, presence: true
validates :body, presence: true, length: {maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:name]

  has_many :books, dependent: :destroy

  has_one_attached :image

  def email_required?
    true
  end

  def will_save_change_to_email?
    false
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, presence: true, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def new
    @book = Books.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @book = Book.new
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_form.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <h3><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, autofocus: true, id:"book_title", class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="book_body">Opinion</label>
          <%= f.text_area :body, autofocus: true, id:"book_body", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div id="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= pluralize(@book.errors.count, "error") %>prohibited this book from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user_info', user: @user %>
      <%= render 'book_form', book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_image(100, 100) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: @book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
  
<% end %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div id="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= pluralize(@book.errors.count, "error") %>prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user_info', user: @user %>
      <%= render 'book_form', book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= image_tag @book.user.get_image(100, 100) %><br>
              <%= link_to @book.user.name, user_path(@book.user) %>
            </td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <td>
            <% if @book.user == current_user %>
              <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
            <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-sm btn-danger" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to 
          <i class="fa-solid fa-book"></i>
          <strong>Bookers</strong>
          !!
        </h1>
        <p>In 
          <i class="fa-solid fa-book"></i>
          <strong>Bookers</strong>
          ,
        </p>
        <p>
          you can share and exchange your opinions, impressions, and emotions
        </p>
        <p>
          about various books!
        </p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/b5424952b8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-home me-1"></i> Home'), user_path(current_user), class: "nav-link text-white" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-users me-1"></i> Users'), users_path, class: "nav-link text-white" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-book-open me-1"></i> Books'), books_path, class: "nav-link text-white" %>
                </li>
                <li class="nav-item">
                   <%= link_to raw('<i class="fa-solid fa-sign-out-alt me-1"></i> Log out'), destroy_user_session_path, method: :delete, class: "nav-link text-white" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-home me-1"></i> Home'), root_path, class: "nav-link text-white" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-link me-1"></i> About'), homes_about_path, class: "nav-link text-white" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-user-plus me-1"></i> Sign up'), new_user_registration_path, class: "nav-link text-white" %>
                </li>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-sign-in-alt me-1"></i> Log in'), new_user_session_path, class: "nav-link text-white" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user_info.html.erb
<h2>User info</h2>
  <% if @user.image.attached? %>
    <%= image_tag @user.image, size: "100x100" %>
  <% else %>
    <%= image_tag 'no_image', size: "100x100" %>
  <% end %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= @user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User info</h1>
      <% if @user.errors.any? %>
        <h3><%= pluralize(@user.errors.count, "error") %> prohibited this book from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id:"user_name", class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :image, accept: "image/*", id: "user_image", class: "form-control-file" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, id:"user?introduction", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_info', user: @user %>
      <%= render 'books/book_form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_image(100, 100) %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_info', user: @user %>
      <%= render 'books/book_form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_image(100, 100) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>